version: '3.8'
services:
  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://backend:3001/api
    ports:
      - '5173:80'
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=mongodb://mongo:27017/textlyzer
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: "passthrough"
    volumes:
      - ./keycloak-data:/opt/keycloak/data/import
    ports:
      - '8080:8080'
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge 