version: '3.8'
services:
  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://backend:3001/api
    ports:
      - '5173:80'
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=mongodb://mongo:27017/textlyzer
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/postgres
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  mongo_data:
  postgres_data:

networks:
  app-network:
    driver: bridge 